import { useState } from 'react';
import { Radar, GitCommit, FileCode, Cpu, AlertTriangle, Info, XCircle, FileText } from 'lucide-react';

export default function DetectionStixPage({ lastResult, cmiConnected }) {
  const [viewMode, setViewMode] = useState('summary');

  const hasResult = Boolean(lastResult);
  const isSuccess = hasResult && lastResult.success && lastResult.data;
  const isFailed = hasResult && !lastResult.success;
  const executionData = isSuccess ? lastResult.data : null;

  return (
    <div className="stix-page font-mono">
      {/* Top Banner */}
      <div className="panel-card banner-card">
        <div className="banner-content">
          <Radar size={20} />
          <div>
            <h3>STIX 2.1 Threat Intelligence & PLTL Engine</h3>
            <p>
              Inspects STIX 2.1 intelligence bundle file paths generated by backend investigation pipeline runs.
            </p>
          </div>
        </div>

        <div className="banner-actions">
          <span className={`badge ${cmiConnected ? 'badge-emerald' : 'badge-warning'}`}>
            {cmiConnected ? 'CMI API: CONNECTED' : 'CMI API: OFFLINE'}
          </span>
          <span className={`badge ${isSuccess ? 'badge-emerald' : isFailed ? 'badge-crimson' : 'badge'}`}>
            {isSuccess ? 'STIX BUNDLE GENERATED' : isFailed ? 'ORCHESTRATION FAILED' : 'NO RESULT'}
          </span>
        </div>
      </div>

      <div className="stix-grid">
        {/* PLTL Logic Rules Notice Panel */}
        <div className="panel-card flex-1">
          <div className="panel-header">
            <div className="panel-title">
              <Cpu size={14} />
              <span>PLTL Temporal Rules & Detection Engine</span>
            </div>
          </div>
          <div className="panel-body">
            <div className="unexposed-box badge badge-warning">
              <AlertTriangle size={13} />
              <div>
                <span className="unexposed-title">Detection Rule Query API Not Exposed</span>
                <p>
                  PLTL temporal rule evaluation is performed internally during backend execution by <code>detection.engine</code> module. 
                  Rule formula lists and individual evaluation metrics are <em>not exposed through current CMI API response schema</em>.
                </p>
              </div>
            </div>
          </div>
        </div>

        {/* STIX 2.1 Details & Raw Inspector */}
        <div className="panel-card flex-2">
          <div className="panel-header">
            <div className="panel-tabs">
              <button 
                className={`tab-btn ${viewMode === 'summary' ? 'active' : ''}`}
                onClick={() => setViewMode('summary')}
              >
                <GitCommit size={12} /> STIX 2.1 Bundle Path
              </button>
              <button 
                className={`tab-btn ${viewMode === 'json' ? 'active' : ''}`}
                onClick={() => setViewMode('json')}
              >
                <FileCode size={12} /> Raw Orchestration Output
              </button>
            </div>
          </div>

          <div className="panel-body">
            {viewMode === 'summary' ? (
              <div className="summary-view">
                {!hasResult && (
                  <div className="empty-state">
                    <Info size={24} className="text-muted" />
                    <p>[+] No STIX 2.1 bundle result available.</p>
                    <p>[+] Go to Jocky Workbench and click "Run Investigation" to generate a STIX bundle.</p>
                  </div>
                )}

                {isFailed && (
                  <div className="failed-state">
                    <div className="failed-banner badge badge-crimson">
                      <XCircle size={14} />
                      <div>
                        <span className="failed-title">STIX 2.1 Output Unavailable</span>
                        <span className="failed-sub">The orchestration pipeline encountered an error prior to STIX generation.</span>
                      </div>
                    </div>
                    <div className="error-details-box">
                      <p><strong>Failed Stage:</strong> {JSON.stringify(lastResult.stage)}</p>
                      <p><strong>Backend Error Output:</strong></p>
                      <pre className="error-pre">{lastResult.error}</pre>
                    </div>
                  </div>
                )}

                {isSuccess && (
                  <div className="success-state">
                    <div className="path-banner badge badge-emerald">
                      <FileText size={14} />
                      <div>
                        <span className="banner-title">STIX 2.1 Intelligence Bundle Path Generated</span>
                        <span className="banner-sub">Backend generated standardized STIX 2.1 file on server filesystem.</span>
                      </div>
                    </div>

                    <div className="info-table">
                      <div className="info-row">
                        <span className="row-label">Investigation ID:</span>
                        <span className="row-val font-bold">{executionData.investigation_id}</span>
                      </div>

                      <div className="info-row">
                        <span className="row-label">Execution Status:</span>
                        <span className="row-val text-success">{executionData.status.toUpperCase()}</span>
                      </div>

                      <div className="info-row">
                        <span className="row-label">Target Platform:</span>
                        <span className="row-val">{executionData.target_platform}</span>
                      </div>

                      <div className="info-row full">
                        <span className="row-label">STIX 2.1 Bundle File Path:</span>
                        <span className="row-val path-box">{executionData.stix_bundle}</span>
                      </div>

                      <div className="info-row full">
                        <span className="row-label">Source System Location:</span>
                        <span className="row-val text-muted">CMI Backend Filesystem (`{executionData.stix_bundle}`)</span>
                      </div>
                    </div>

                    <div className="disclosure-box">
                      <AlertTriangle size={13} className="text-amber" />
                      <div>
                        <p><strong>API Availability & STIX Content Disclosure:</strong></p>
                        <ul>
                          <li>STIX bundle file path generated: <code>{executionData.stix_bundle}</code>.</li>
                          <li>Individual STIX Domain Objects (SDOs), Cyber Observables (SCOs), indicators, and relationships are stored inside the server-side JSON file and are <em>not exposed by current CMI API response schema</em>.</li>
                          <li>Direct browser download of STIX bundle is <em>not exposed by current CMI API</em>.</li>
                        </ul>
                      </div>
                    </div>
                  </div>
                )}
              </div>
            ) : (
              <div className="raw-view">
                {hasResult ? (
                  <pre className="json-pre">{JSON.stringify(lastResult, null, 2)}</pre>
                ) : (
                  <div className="empty-state">
                    <p>[!] No backend response data recorded for current session.</p>
                  </div>
                )}
              </div>
            )}
          </div>
        </div>
      </div>

      <style>{`
        .stix-page {
          display: flex;
          flex-direction: column;
          gap: 14px;
        }

        .banner-card {
          padding: 14px 16px;
          display: flex;
          align-items: center;
          justify-content: space-between;
        }

        .banner-content {
          display: flex;
          align-items: center;
          gap: 12px;
        }

        .banner-content h3 {
          font-size: 13.5px;
          color: var(--text-primary);
          font-weight: 700;
        }

        .banner-content p {
          font-size: 10.5px;
          color: var(--text-secondary);
        }

        .banner-actions {
          display: flex;
          gap: 6px;
        }

        .stix-grid {
          display: flex;
          gap: 14px;
        }

        .flex-1 { flex: 1; }
        .flex-2 { flex: 2; }

        .unexposed-box {
          display: flex;
          gap: 8px;
          padding: 10px;
          font-size: 10.5px;
          color: var(--text-secondary);
          line-height: 1.4;
          width: 100%;
        }

        .unexposed-title {
          font-weight: 700;
          display: block;
          margin-bottom: 2px;
          color: var(--text-primary);
        }

        .panel-tabs {
          display: flex;
          gap: 4px;
        }

        .tab-btn {
          display: flex;
          align-items: center;
          gap: 4px;
          padding: 4px 8px;
          background: transparent;
          border: none;
          color: var(--text-muted);
          font-size: 11px;
          font-weight: 700;
          cursor: pointer;
          border-bottom: 2px solid transparent;
        }

        .tab-btn.active {
          color: var(--text-primary);
          border-bottom-color: var(--accent);
        }

        .path-banner, .failed-banner {
          display: flex;
          align-items: center;
          gap: 10px;
          padding: 8px 12px;
          margin-bottom: 12px;
          width: 100%;
        }

        .banner-title, .failed-title {
          font-size: 11px;
          font-weight: 700;
          display: block;
        }

        .banner-sub, .failed-sub {
          font-size: 9.5px;
          color: var(--text-secondary);
        }

        .info-table {
          display: flex;
          flex-direction: column;
          gap: 8px;
          background: var(--bg-primary);
          border: 1px solid var(--border-color);
          padding: 10px;
          margin-bottom: 12px;
        }

        .info-row {
          display: flex;
          gap: 10px;
          font-size: 10.5px;
          align-items: baseline;
        }

        .info-row.full {
          flex-direction: column;
          gap: 3px;
        }

        .row-label {
          font-size: 9.5px;
          font-weight: 700;
          color: var(--text-muted);
          min-width: 140px;
        }

        .row-val {
          color: var(--text-primary);
        }

        .path-box {
          background: var(--bg-secondary);
          border: 1px solid var(--border-color);
          padding: 4px 8px;
          width: 100%;
          word-break: break-all;
        }

        .disclosure-box {
          display: flex;
          gap: 10px;
          background: var(--bg-primary);
          border: 1px solid var(--border-color);
          border-left: 3px solid var(--status-warning);
          padding: 10px;
          font-size: 10px;
          color: var(--text-secondary);
          line-height: 1.5;
        }

        .disclosure-box ul {
          padding-left: 16px;
          margin-top: 4px;
        }

        .json-pre {
          background: var(--bg-primary);
          padding: 10px;
          border: 1px solid var(--border-color);
          color: var(--text-secondary);
          font-size: 10.5px;
          max-height: 300px;
          overflow-y: auto;
        }

        .empty-state {
          padding: 30px 20px;
          text-align: center;
          color: var(--text-muted);
          font-size: 11px;
          display: flex;
          flex-direction: column;
          align-items: center;
          gap: 6px;
        }

        .failed-state {
          display: flex;
          flex-direction: column;
          gap: 8px;
        }

        .error-details-box {
          background: var(--bg-primary);
          border: 1px solid var(--border-color);
          padding: 10px;
          font-size: 10.5px;
        }

        .error-pre {
          color: var(--status-error);
          background: var(--bg-secondary);
          border: 1px solid var(--border-color);
          padding: 6px;
          margin-top: 4px;
          max-height: 150px;
          overflow-y: auto;
          white-space: pre-wrap;
          word-break: break-all;
        }

        .text-success { color: var(--status-success); }
        .text-amber { color: var(--status-warning); }
        .font-bold { font-weight: 700; }
      `}</style>
    </div>
  );
}
