import { useState } from 'react';
import { FolderLock, ShieldCheck, Download, FileJson, Lock, AlertTriangle } from 'lucide-react';

export default function EvidencePage() {
  const [activeTab, setActiveTab] = useState('sealed');

  const mockSealedEvidence = {
    investigation_id: "NTRO-Sweep-A81F92",
    timestamp_utc: "2026-09-27T12:45:00Z",
    operator_id: "local-operator",
    platform: "Linux (x86_64)",
    provider: "Linux Provider",
    chain_of_custody: {
      integrity_seal_version: "v1.0-SHA256",
      verified: true,
      custodian: "Mahoraga Evidence Sealing Module",
    },
    sealed_artifacts: [
      {
        capability: "process_list",
        sha256: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
        record_count: 142,
      },
      {
        capability: "system_info",
        sha256: "88d4266fd4e6338d13b845fcf289579d209c897823b9217da3e161936f031589",
        record_count: 1,
      },
      {
        capability: "network_connections",
        sha256: "4b227777d4dd1fc61c6f884f48641d02b4d121d3fd328cb08b5531fcacdabf8a",
        record_count: 38,
      },
    ]
  };

  return (
    <div className="evidence-page">
      {/* Top Banner */}
      <div className="panel-card banner-card">
        <div className="banner-content">
          <FolderLock size={20} />
          <div>
            <h3>Cryptographic Evidence Vault & Chain-of-Custody</h3>
            <p>
              Preserves collected forensic artifacts through SHA-256 integrity hashing and tamper-proof sealing.
            </p>
          </div>
        </div>

        <div className="banner-actions">
          <span className="badge badge-warning">BACKEND DISCONNECTED (DEMO)</span>
          <button className="btn btn-primary">
            <Download size={12} /> Export Air-Gapped Package (.zip)
          </button>
        </div>
      </div>

      {/* Main Evidence Grid */}
      <div className="evidence-grid">
        {/* Left List of Evidence Bundles */}
        <div className="panel-card flex-1">
          <div className="panel-header">
            <div className="panel-title">
              <FileJson size={14} />
              <span>Sealed Evidence Bundles</span>
            </div>
          </div>
          <div className="panel-body">
            <div className="bundle-list">
              <div className="bundle-item active">
                <div className="bundle-top">
                  <span className="bundle-id">NTRO-Sweep-A81F92</span>
                  <span className="badge badge-emerald">SEALED</span>
                </div>
                <div className="bundle-bottom">
                  <span>host_sweep.jocky</span>
                  <span>3 artifacts</span>
                </div>
              </div>

              <div className="bundle-item">
                <div className="bundle-top">
                  <span className="bundle-id">NTRO-Sweep-73B01C</span>
                  <span className="badge badge-emerald">SEALED</span>
                </div>
                <div className="bundle-bottom">
                  <span>hunt.jocky</span>
                  <span>2 artifacts</span>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Right Evidence Inspector */}
        <div className="panel-card flex-2">
          <div className="panel-header">
            <div className="panel-tabs">
              <button 
                className={`tab-btn ${activeTab === 'sealed' ? 'active' : ''}`}
                onClick={() => setActiveTab('sealed')}
              >
                <ShieldCheck size={12} /> Sealed Artifacts & Hashes
              </button>
              <button 
                className={`tab-btn ${activeTab === 'raw' ? 'active' : ''}`}
                onClick={() => setActiveTab('raw')}
              >
                <FileJson size={12} /> Raw Evidence JSON
              </button>
            </div>
          </div>

          <div className="panel-body">
            {activeTab === 'sealed' ? (
              <div className="sealed-view">
                <div className="custody-banner badge badge-emerald">
                  <Lock size={14} />
                  <div>
                    <span className="custody-title">Chain of Custody Status: VERIFIED</span>
                    <span className="custody-sub">
                      SHA-256 hashes generated by Mahoraga evidence module on {mockSealedEvidence.timestamp_utc}
                    </span>
                  </div>
                </div>

                <div className="hash-table">
                  <div className="hash-table-header">
                    <span>CAPABILITY</span>
                    <span>RECORDS</span>
                    <span>SHA-256 INTEGRITY DIGEST</span>
                  </div>
                  {mockSealedEvidence.sealed_artifacts.map((art, idx) => (
                    <div key={idx} className="hash-row">
                      <span className="art-name">{art.capability}</span>
                      <span className="art-count">{art.record_count}</span>
                      <span className="art-hash">{art.sha256}</span>
                    </div>
                  ))}
                </div>
              </div>
            ) : (
              <div className="raw-view">
                <div className="notice-box badge badge-warning">
                  <AlertTriangle size={13} />
                  <span>
                    Raw evidence payload preview. Connect CMI server (`python -m cmi.server`) to fetch live system data.
                  </span>
                </div>
                <pre className="json-pre">{JSON.stringify(mockSealedEvidence, null, 2)}</pre>
              </div>
            )}
          </div>
        </div>
      </div>

      <style>{`
        .evidence-page {
          display: flex;
          flex-direction: column;
          gap: 14px;
        }

        .banner-card {
          padding: 14px 16px;
          display: flex;
          align-items: center;
          justify-content: space-between;
        }

        .banner-content {
          display: flex;
          align-items: center;
          gap: 12px;
        }

        .banner-content h3 {
          font-size: 13.5px;
          color: var(--text-primary);
          font-weight: 700;
        }

        .banner-content p {
          font-size: 10.5px;
          color: var(--text-secondary);
        }

        .banner-actions {
          display: flex;
          align-items: center;
          gap: 8px;
        }

        .evidence-grid {
          display: flex;
          gap: 14px;
        }

        .flex-1 { flex: 1; }
        .flex-2 { flex: 2; }

        .bundle-list {
          display: flex;
          flex-direction: column;
          gap: 6px;
        }

        .bundle-item {
          padding: 8px;
          background: var(--bg-primary);
          border: 1px solid var(--border-color);
          cursor: pointer;
          transition: border-color 0.15s ease;
        }

        .bundle-item:hover {
          border-color: var(--accent);
        }

        .bundle-item.active {
          border-color: var(--accent);
          background: var(--bg-tertiary);
        }

        .bundle-top {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: 3px;
        }

        .bundle-id {
          font-size: 10.5px;
          font-weight: 700;
          color: var(--text-primary);
        }

        .bundle-bottom {
          display: flex;
          justify-content: space-between;
          font-size: 9.5px;
          color: var(--text-muted);
        }

        .panel-tabs {
          display: flex;
          gap: 4px;
        }

        .tab-btn {
          display: flex;
          align-items: center;
          gap: 4px;
          padding: 4px 8px;
          background: transparent;
          border: none;
          color: var(--text-muted);
          font-size: 11px;
          font-weight: 700;
          cursor: pointer;
          border-bottom: 2px solid transparent;
        }

        .tab-btn.active {
          color: var(--text-primary);
          border-bottom-color: var(--accent);
        }

        .custody-banner {
          display: flex;
          align-items: center;
          gap: 10px;
          padding: 8px 12px;
          margin-bottom: 12px;
          width: 100%;
        }

        .custody-title {
          font-size: 11px;
          font-weight: 700;
          color: var(--text-primary);
          display: block;
        }

        .custody-sub {
          font-size: 9.5px;
          color: var(--text-secondary);
        }

        .hash-table {
          display: flex;
          flex-direction: column;
          background: var(--bg-primary);
          border: 1px solid var(--border-color);
        }

        .hash-table-header {
          display: grid;
          grid-template-columns: 140px 70px 1fr;
          gap: 8px;
          padding: 6px 10px;
          background: var(--bg-secondary);
          border-bottom: 1px solid var(--border-color);
          font-size: 9.5px;
          font-weight: 700;
          color: var(--text-muted);
        }

        .hash-row {
          display: grid;
          grid-template-columns: 140px 70px 1fr;
          gap: 8px;
          padding: 6px 10px;
          border-bottom: 1px solid var(--border-color);
          font-size: 10.5px;
          align-items: center;
        }

        .art-name { color: var(--text-primary); font-weight: 600; }
        .art-count { color: var(--text-secondary); }
        .art-hash { color: var(--text-secondary); font-size: 9.5px; overflow: hidden; text-overflow: ellipsis; }

        .notice-box {
          display: flex;
          align-items: center;
          gap: 6px;
          padding: 8px 10px;
          font-size: 10.5px;
          color: var(--text-secondary);
          margin-bottom: 10px;
          width: 100%;
        }

        .json-pre {
          background: var(--bg-primary);
          padding: 10px;
          border: 1px solid var(--border-color);
          color: var(--text-secondary);
          font-size: 10.5px;
          max-height: 280px;
          overflow-y: auto;
        }
      `}</style>
    </div>
  );
}
